name: Hourly Install Schedule

on:
  schedule:
    # Trigger the job every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Manual trigger

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run: [1, 2, 3, 4, 5]
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run npm install
        run: |
          echo "Running npm install - Run ${{ matrix.run }} of 5"
          npm i react-smart-conditional
