name: Hourly Install Schedule

on:
  schedule:
    # Trigger the job every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Manual trigger

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run npm install
        run: |
          for i in {1..20}
          do
            npm install react-smart-conditional
          done
